export const MUTATIONS_TYPES = {
  SET_SITUATION_FIRST_STEP: "SET_SITUATION_FIRST_STEP",
  SET_SITUATION_SECOND_STEP: "SET_SITUATION_SECOND_STEP",
  SET_SITUATION_THIRD_STEP: "SET_SITUATION_THIRD_STEP",
  SET_SITUATION_FIELD: "SET_SITUATION_FIELD"
};

export const ACTIONS_TYPES = {
  CHANGE_SITUATION_FIELD: "CHANGE_SITUATION_FIELD"
};
