export const MUTATIONS_TYPES = {
  SET_CURRENT_ROUTE: "SET_CURRENT_ROUTE",
  SET_ACCESS_TOKEN: "SET_ACCESS_TOKEN",
  SET_USER_PROFILE: "SET_USER_PROFILE",
  SET_USER: "SET_USER",
  SET_SELECTED_CASE: "SET_SELECTED_CASE",
  SET_PRECASE: "SET_PRECASE",
  SET_IS_FETCHING: "SET_IS_FETCHING",
  SET_IS_FETCHING_USER: "SET_IS_FETCHING_USER",
  SET_IS_FETCHING_CASES_TO_EXPORT: "SET_IS_FETCHING_CASES_TO_EXPORT",
  SET_IS_SESSION_EXPIRED: "SET_IS_SESSION_EXPIRED",
  SET_COLLECTIONS: "SET_COLLECTIONS",
  SET_EMPLOYEES: "SET_EMPLOYEES",
  SET_IS_FETCHING_FROM_INFO: "SET_IS_FETCHING_FROM_INFO",
  ADD_CASE_TO_SELECTION: "ADD_CASE_TO_SELECTION",
  REMOVE_CASE_FROM_SELECTION: "REMOVE_CASE_FROM_SELECTION",
  SET_CASE_SELECTION: "SET_CASE_SELECTION",
  SET_SEARCH_RESULTS: "SET_SEARCH_RESULTS",
  SET_CASES_TO_EXPORT: "SET_CASES_TO_EXPORT",
  SET_SEARCH_ROUTE: "SET_SEARCH_ROUTE"
};

export const ACTIONS_TYPES = {
  FETCH_URL_VALUES: "FETCH_URL_VALUES",
  ROUTER_PUSH: "ROUTER_PUSH",
  ROUTER_REPLACE: "ROUTER_REPLACE",
  GET_SIGNED_IN_USER: "GET_SIGNED_IN_USER",
  GET_USER_BY_TOKEN: "GET_USER_BY_TOKEN",
  REFRESH_USER_ACCESS_TOKEN: "REFRESH_USER_ACCESS_TOKEN",
  FETCH_COLLECTIONS: "FETCH_COLLECTIONS",
  SEARCH_CASES: "SEARCH_CASES",
  FETCH_SELECTED_CASES: "FETCH_SELECTED_CASES"
};
