export enum MetricsFields {
  ADDRESABLE_BASELINE = "metricsAddresableBaseline",
  AMOUNT_DEBT_BEFORE_INVOLMENT = "metricsAmountDebtBeforeInvolvement",
  AMOUNT_DEBT_REFINANCED = "metricsAmountDebtRefinanced",
  APPLICATIONS_RATIONALIZED = "metricsApplicationsRationalized",
  COST_REDUCTION_ACHIEVED = "metricsCostReductionAchieved",
  COST_REDUCTION_IDENTIFIED = "metricsCostReductionIdentified",
  DAYS_IN_CHE11 = "metricsDaysInCh11",
  DEBT_REFINANCED = "metricsDebtRefinanced",
  EBITDA = "metricsEBITDA",
  NUMBER_CLAIMANTS = "metricsNumberClaimants",
  NUMBER_CLAIMS_SETTLED = "metricsNumberClaimsSettled",
  PERCENT_REVENUE_INCREASE_ACHIEVED = "metricsPercentRevenueIncreaseAchieved",
  PERCENT_REVENUE_INCREASE_IDENTIFIED = "metricsPercentRevenueIncreaseIdentified",
  REDUCED_WORKING_CAPITAL = "metricsReducedWorkingCapital",
  REVENUE_INCREASE_ACHIEVED = "metricsRevenueIncreaseAchieved",
  REVENUE_INCREASE_IDENTIFIED = "metricsRevenueIncreaseIdentified",
  TERABYTES_ANALYZED = "metricsTerabytesAnalyzed",
  WEEKS_TO_ACHIEVE_RESULT = "metricsWeeksToAchieveResults"
}
