export const MUTATIONS_TYPES = {
  SET_NOTIFICATIONS_VISUALIZATION: "SET_NOTIFICATIONS_VISUALIZATION",
  SET_NOTIFICATIONS_LIST: "SET_NOTIFICATIONS_LIST",
  SET_NOTIFICATION_AS_READ: "SET_NOTIFICATION_AS_READ",
  SET_ALL_NOTIFICATIONS_AS_READ: "SET_ALL_NOTIFICATIONS_AS_READ"
};

export const ACTIONS_TYPES = {
  FETCH_NOTIFICATIONS: "FETCH_NOTIFICATIONS",
  PATCH_NOTIFICATION_AS_READ: "PATCH_NOTIFICATION_AS_READ",
  SET_ALL_NOTIFICATIONS_AS_READ: "SET_ALL_NOTIFICATIONS_AS_READ"
};
