export const MUTATIONS_TYPES = {
  SET_CLIENT_INFO_FIRST_STEP: "SET_CLIENT_INFO_FIRST_STEP",
  SET_CLIENT_INFO_SECOND_STEP: "SET_CLIENT_INFO_SECOND_STEP",
  SET_CLIENT_INFO_FIELD: "SET_CLIENT_INFO_FIELD"
};

export const ACTIONS_TYPES = {
  CHANGE_CLIENT_INFO_FIELD: "CHANGE_CLIENT_INFO_FIELD"
};
