export const MUTATIONS_TYPES = {
  ADD_ERROR: "ADD_ERROR",
  REMOVE_ERROR: "REMOVE_ERROR",
  SET_IS_ERROR: "SET_IS_ERROR",
  SET_PRIMARY_STEP: "SET_PRIMARY_STEP",
  SET_SECONDARY_STEP: "SET_SECONDARY_STEP",
  SET_THIRD_STEP: "SET_THIRD_STEP",
  SET_EDIT_MODE: "SET_EDIT_MODE",
  UPLOAD_CHART: "UPLOAD_CHART",
  FETCH_FILE: "FETCH_FILE",
  DELETE_FILE: "DELETE_FILE",
  IS_EDITING_METRIC: "IS_EDITING_METRIC",
  SET_IS_FETCHING_CLIENT_INFO: "SET_IS_FETCHING_CLIENT_INFO"
};

export const ACTIONS_TYPES = {
  SET_CASE_QUESTIONS: "SET_CASE_QUESTIONS",
  SUBMIT_CASE: "SUBMIT_CASE",
  OPEN_CASE: "OPEN_CASE",
  APPROVE_CASE_MD: "APPROVE_CASE_MD",
  APPROVE_CASE_KM: "APPROVE_CASE_KM",
  PUBLISH_CASE: "PUBLISH_CASE",
  CHANGE_SECONDARY_STEP: "CHANGE_SECONDARY_STEP",
  FETCH_CASE_DETAILS: "FETCH_CASE_DETAILS",
  ADD_STARTER_TEXT: "ADD_STARTER_TEXT",
  PATCH_CASE_DETAILS: "PATCH_CASE_DETAILS",
  UPDATE_CASE_DETAILS: "UPDATE_CASE_DETAILS",
  UPLOAD_CHART: "UPLOAD_CHART",
  FETCH_FILE: "FETCH_FILE",
  DELETE_FILE: "DELETE_FILE",
  HANDLE_EDIT_MODE: "HANDLE_EDIT_MODE"
};
