export const MUTATIONS_TYPES = {
  SET_APPROACH_FIRST_STEP: "SET_APPROACH_FIRST_STEP",
  SET_APPROACH_SECOND_STEP: "SET_APPROACH_SECOND_STEP",
  SET_APPROACH_FIELD: "SET_APPROACH_FIELD"
};

export const ACTIONS_TYPES = {
  CHANGE_APPROACH_FIELD: "CHANGE_APPROACH_FIELD"
};
