export const MUTATIONS_TYPES = {
  SET_MESSAGE: "SET_MESSAGE",
  SET_MENU_OPEN: "SET_MENU_OPEN",
  SHOWN_CLIENT_INFO: "SHOWN_CLIENT_INFO",
  SHOWN_INTRO_STEPS: "SHOWN_INTRO_STEPS"
};

export const ACTIONS_TYPES = {
  SHOW_MESSAGE: "SHOW_MESSAGE",
  HANDLE_CASE_INTRO: "HANDLE_CASE_INTRO"
};
