export const ACTIONS_TYPES = {
  FETCH_PRECASE: "FETCH_PRECASE",
  REJECT_CASE: "REJECT_CASE",
  POST_PRECASE: "POST_PRECASE",
  FETCH_EMPLOYEES: "FETCH_EMPLOYEES"
};

export const MUTATIONS_TYPES = {};
